#lang racket
(require (only-in (file "tokenize-bonus.rkt") tokenize))
(define tokens null)
(define new_tokens null)
(define temp null)
(define temp_tok null)
(define name null)
(define expr_tok null)

(define (consume type)
  (when (empty? tokens)
    (error (~a "expected token of type " type " but no remaining tokens")))
  (let ([token (first tokens)])
    (when (not (equal? type (first token)))
      ;;(error (~a "expected token of type " type " but actual token was " token)))
      #f)
    (set! tokens (rest tokens))  ; update tokens: remove first token
    token))

(define (check type)
  ;;(display type)
  ;;(display tokens)
  (if (empty? tokens)
      #f
      (begin
        (equal? type (first (first tokens))))
      )
  )
(define (atom-pending)
  (or (check 'NAME) (check 'STRING) (check 'INT) (check 'FLOAT))
  )
      
(define (invocation-pending)
  (check 'OPAREN)
  )

(define (invocation-tail-define-pending)
  (check 'DEFINE)
  )

(define (invocation-tail)
  (if (or (equal? #t (atom-pending)) (equal? #t (invocation-pending)))
      (list 'invocationTail (exprlist) '(CPAREN #f))
      (begin
        (consume 'DEFINE)
        (set! name (first tokens))
        (consume 'NAME)
        (set! expr_tok (expr))
        (consume 'CPAREN)
        (list 'invocationTail '(DEFINE #f) name expr_tok '(CPAREN #f)))
        )
  )
      

(define (invocation)
  (begin
    (consume 'OPAREN)
    (set! temp (invocation-tail))
    (list 'invocation '(OPAREN #f) temp)
    )
  )

(define (expr)
  (if (or (equal? #t (atom-pending)) (equal? #t (invocation-pending)))
      (if (equal? #t (atom-pending))
          (if (or (equal? #t (check 'NAME)) (equal? #t (check 'STRING)))
              (begin
                (set! temp_tok (first tokens))
                (consume (first (first tokens)))
                (list 'expr (list 'atom temp_tok))
                )
              (begin
                (set! temp_tok (first tokens)) 
                (consume (first (first tokens)))
                (list 'expr (list 'atom (list 'number temp_tok)))
                )
              )
          (list 'expr (invocation))
          )
      #f
      )
  )
      
(define (optexprlist)
  (if (or (equal? #t (atom-pending)) (equal? #t (invocation-pending)))
      (list 'optExprList (exprlist))
      (list 'optExprList)
      )
  )

(define (exprlist)
  (list 'exprList (expr) (optexprlist))

 )

(define (parse2 str)
  (set! tokens null)
  (set! new_tokens '())
  (set! temp null)
  (set! temp_tok null)
  (set! name null)
  (set! expr_tok null)
  (set! tokens (tokenize str))
  (for ([e (in-list tokens)])
    (if (equal? '(define) (rest e))
        (set! new_tokens (append new_tokens (list (list 'DEFINE #f))))
        (set! new_tokens (append new_tokens (list e)))
        )
    )
  (set! tokens new_tokens)
  (list 'program (exprlist))
  )